name: Synergy
main: me.synergy.brains.Spigot
version: ${project.version}
api-version: 1.16
author: mrbear22
softdepend: [Authme, PlaceholderAPI, ProtocolLib, Votifier, Essentials, Vault, Plan, Factions]
description: ${project.description}
commands:
  synergy:
    description: <lang>command_description_synergy</lang>
    usage: <lang>command_usage_synergy</lang>
  vote:
    description: <lang>command_description_vote</lang>
    usage: <lang>command_usage_vote</lang>
  chat:
    description: <lang>command_description_chat</lang>
    usage: <lang>command_usage_chat</lang>
  theme:
    description: <lang>command_description_theme</lang>
    usage: <lang>command_usage_theme</lang>
  colors:
    description: <lang>command_description_colors</lang>
    usage: <lang>command_usage_colors</lang>
  emojis:
    description: <lang>command_description_emojis</lang>
    usage: <lang>command_usage_emojis</lang>
  chatfilter:
    description: <lang>command_description_chatfilter</lang>
    usage: <lang>command_usage_chatfilter</lang>
  discord:
    description: <lang>command_description_discord</lang>
    usage: <lang>command_usage_discord</lang>
  twitch:
    description: <lang>command_description_twitch</lang>
    usage: <lang>command_usage_twitch</lang>
  tiktok:
    description: <lang>command_description_tiktok</lang>
    usage: <lang>command_usage_tiktok</lang>
  monobank:
    description: <lang>command_description_monobank</lang>
    usage: <lang>command_usage_monobank</lang>
  language:
    description: <lang>command_description_language</lang>
    usage: <lang>command_usage_language</lang>
    aliases: [lang]
  pronoun:
    description: <lang>command_description_pronoun</lang>
    usage: <lang>command_usage_pronoun</lang>
    aliases: [gender, iamgirl, iamboy]